#pragma once

/*
    This file was auto-generated by the magic optimized FIR script.
    DO NOT EDIT MANUALLY!!!
*/

namespace dsp::multirate::decim {
    const unsigned int fir_4_2_len = 10;
    const float fir_4_2_taps[] = {
        -0.014764914583446,
        -0.034930176866210,
        0.097375843136160,
        -0.158353146254340,
        0.202701914619528,
        0.801176045313171,
        0.202701914619528,
        -0.158353146254340,
        0.097375843136160,
        -0.034930176866210,
    };
}
